package com.mss.unified.entities;

import org.jpos.iso.*;

public class ISO93APackager extends ISOBasePackager {
    protected ISOFieldPackager[] fld = {
            /*000*/ new IFA_NUMERIC(4, "Message Type Indicator"),
            /*001*/ new IFA_BITMAP(64, "Bitmap"),
            /*002*/ new IFA_LLNUM(19, "Primary Account number"),
            /*003*/ new IFA_NUMERIC(6, "Processing Code"),
            /*004*/ new IFA_NUMERIC(12, "Amount, Transaction"),
            /*005*/ new IFA_NUMERIC(12, "Amount, Reconciliation"),
            /*006*/ null,
            /*007*/ new IFA_NUMERIC(10, "Transmission date and time"),
            /*008*/ null,
            /*009*/ null,
            /*010*/ null,
            /*011*/ new IFA_NUMERIC(6, "Systems Trace Audit Number"),
            /*012*/ new IFA_NUMERIC(12, "Transaction local date and time"),
            /*013*/ null,
            /*014*/ new IFA_NUMERIC(4, "Expiry date"),
            /*015*/ new IFA_NUMERIC(6, "Settlement date"),
            /*016*/ null,
            /*017*/ new IFA_NUMERIC(4, "Capture date"),
            /*018*/ null,
            /*019*/ null,
            /*020*/ null,
            /*021*/ null,
            /*022*/ new IFA_LLCHAR(12, "POS Entry mode"),
            /*023*/ new IFA_NUMERIC(3, "Pan Sequence Number"),
            /*024*/ new IFA_NUMERIC(3, "Function Code"),
            /*025*/ new IFA_NUMERIC(4, "Message reason code"),
            /*026*/ new IFA_NUMERIC(4, "Merchant business code"),
            /*027*/ null,
            /*028*/ null,
            /*029*/ null,
            /*030*/ new IFA_NUMERIC(24, "Replacement amounts"),
            /*031*/ null,
            /*032*/ new IFA_LLCHAR(11, "Acquiring institution identification code"),
            /*033*/ null,
            /*034*/ new IFA_LLCHAR(28, "Primary account number extension"),
            /*035*/ new IFA_LLCHAR(37, "Track 2 data"),
            /*036*/ null,
            /*037*/ new IFA_NUMERIC(12, "Retrieval reference number"),
            /*038*/ new IFA_NUMERIC(6, "Approval code"),
            /*039*/ new IFA_NUMERIC(3, "Action code"),
            /*040*/ null,
            /*041*/ new IF_CHAR(8, "Card acceptor device identification"),
            /*042*/ new IF_CHAR(15, "Card acceptor identification"),
            /*043*/ new IFA_LLCHAR(99, "Card acceptor name and address"),
            /*044*/ new IFB_LLCHAR(99, "Additional response data"),
            /*045*/ null,
            /*046*/ new IFA_LLLCHAR(204, "Fees amount"),
            /*047*/ null,
            /*048*/ new IFA_LLLCHAR(999, "Provide Additional Data"),
            /*049*/ new IFA_NUMERIC(3, "Transaction currency code"),
            /*050*/ new IFA_NUMERIC(3, "Settlement currency code"),
            /*051*/ null,
            /*052*/ new IFA_BINARY(8, "Pin Data"),
            /*053*/ new IFB_LLCHAR(18, "Security data"),
            /*054*/ new IFA_LLLCHAR(120, "Additional amounts"),
            /*055*/ new IFA_LLLBINARY(255, "Smart Card Information"),
            /*056*/ new IFA_LLNUM(45, "Original data elements"),
            /*057*/ null,
            /*058*/ null,
            /*059*/ null,
            /*060*/ null,
            /*061*/ null,
            /*062*/ new IFA_LLLCHAR(999, "Redemption number"),
            /*063*/ new IFB_LLLCHAR(999, "Versions"),
            /*064*/ new IFA_BINARY(8, "Message Authentication Code"),
            /*065*/ null,
            /*066*/ null,
            /*067*/ null,
            /*068*/ null,
            /*069*/ null,
            /*071*/ new IFA_NUMERIC(8, "Message number"),
            /*070*/ null,
            /*072*/ new IFB_LLLCHAR(999, "Data record"),
            /*073*/ new IFA_NUMERIC(6, "Action date"),
            /*074*/ new IFA_NUMERIC(10, "Credits number"),
            /*075*/ new IFA_NUMERIC(10, "Credits reversal number"),
            /*076*/ new IFA_NUMERIC(10, "Debit number"),
            /*077*/ new IFA_NUMERIC(10, "Debits reversal number"),
            /*079*/ null,
            /*078*/ null,
            /*080*/ null,
            /*082*/ null,
            /*081*/ null,
            /*083*/ new IFA_NUMERIC(10, "Payments number"),
            /*085*/ null,
            /*084*/ new IFA_NUMERIC(10, "Payments reversal number"),
            /*086*/ new IFA_NUMERIC(16, "Credits amount"),
            /*087*/ new IFA_NUMERIC(16, "Credits recycled amounts"),
            /*088*/ new IFA_NUMERIC(16, "Debits amount"),
            /*090*/ null,
            /*089*/ new IFA_NUMERIC(16, "Debits reversed amounts"),
            /*091*/ null,
            /*093*/ null,
            /*094*/ null,
            /*092*/ null,
            /*096*/ null,
            /*095*/ null,
            /*097*/ new IFA_LLCHAR(16, "Net reconciliation amount"),
            /*099*/ null,
            /*098*/ null,
            /*100*/ null,
            /*102*/ null,
            /*101*/ new IFB_LLCHAR(17, "File name"),
            /*103*/ null,
            /*105*/ null,
            /*104*/ null,
            /*106*/ null,
            /*108*/ null,
            /*107*/ null,
            /*109*/ null,
            /*111*/ null,
            /*110*/ new IFA_LLLBINARY(999, "Data capture linked to ICC cards"),
            /*112*/ null,
            /*113*/ null,
            /*114*/ null,
            /*115*/ null,
            /*116*/ null,
            /*117*/ null,
            /*118*/ null,
            /*119*/ null,
            /*120*/ null,
            /*121*/ null,
            /*122*/ null,
            /*123*/ null,
            /*124*/ null,
            /*125*/ null,
            /*126*/ null,
            /*127*/ null,
            /*128*/ new IF_CHAR(8, "Message Authentication Code"),
};



    public ISO93APackager() {
        super();

        setFieldPackager(fld);
    }




}


